[[pages]]
path = "Home.py"
name = "Home"
icon = ""

[[pages]]
path = "pages/Customer Concessions.py"
name = "Customer Concessions"
icon = ""

[[pages]]
path = "pages/Customer Surveys.py"
name = "Customer Surveys"
icon = ""

[[pages]]
path = "pages/Downtime.py"
name = "Downtime"
icon = ""

[[pages]]
path = "pages/Lead Times.py"
name = "Lead Times"
icon = ""

[[pages]]
path = "pages/On-time Delivery.py"
name = "On-time Delivery"
icon = ""

[[pages]]
path = "pages/Production.py"
name = "Production"
icon = ""

[[pages]]
path = "pages/Safety.py"
name = "Safety"
icon = ""

[[pages]]
path = "pages/Shipping.py"
name = "Shipping"
icon = ""

[[pages]]
path = "pages/Print Summary.py"
name = "Print Summary"
icon = ""